env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
ignorePatterns:
  - dist
  - /*.config.(js|ts)
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - react
  - react-hooks
  - react-refresh
rules:
  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true
  react/react-in-jsx-scope: off
